package fr.polytech.polydiploma.remote.stubs;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-05-01T19:16:29.326+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum", name = "AlumWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface AlumWebService {

    @WebMethod
    @RequestWrapper(localName = "confirmAttendance", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum", className = "fr.polytech.polydiploma.remote.stubs.ConfirmAttendance")
    @ResponseWrapper(localName = "confirmAttendanceResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum", className = "fr.polytech.polydiploma.remote.stubs.ConfirmAttendanceResponse")
    @WebResult(name = "attendance_confirmed", targetNamespace = "")
    public boolean confirmAttendance(
        @WebParam(name = "graduate", targetNamespace = "")
        fr.polytech.polydiploma.remote.stubs.Graduate graduate
    );

    @WebMethod
    @RequestWrapper(localName = "addGuest", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum", className = "fr.polytech.polydiploma.remote.stubs.AddGuest")
    @ResponseWrapper(localName = "addGuestResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum", className = "fr.polytech.polydiploma.remote.stubs.AddGuestResponse")
    @WebResult(name = "guest_added", targetNamespace = "")
    public boolean addGuest(
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "guestFirstName", targetNamespace = "")
        java.lang.String guestFirstName,
        @WebParam(name = "guestLastName", targetNamespace = "")
        java.lang.String guestLastName
    );

    @WebMethod
    @RequestWrapper(localName = "payBalance", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum", className = "fr.polytech.polydiploma.remote.stubs.PayBalance")
    @ResponseWrapper(localName = "payBalanceResponse", targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum", className = "fr.polytech.polydiploma.remote.stubs.PayBalanceResponse")
    @WebResult(name = "amount_paid", targetNamespace = "")
    public double payBalance(
        @WebParam(name = "email", targetNamespace = "")
        java.lang.String email,
        @WebParam(name = "extraData", targetNamespace = "")
        java.lang.String extraData
    );
}
