package fr.polytech.polydiploma.remote.stubs;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2019-04-26T11:07:55.538+02:00
 * Generated source version: 3.1.10
 * 
 */
@WebServiceClient(name = "AlumWebServiceImplService", 
                  wsdlLocation = "file:/Users/alexandre/Desktop/Code/Polytech/ISA%20DevOps/ClientAlum/src/main/resources/AlumWS.wsdl",
                  targetNamespace = "http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum") 
public class AlumWebServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum", "AlumWebServiceImplService");
    public final static QName AlumWebServiceImplPort = new QName("http://www.polytech.unice.fr/si/4a/isa/polydiploma/alum", "AlumWebServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/Users/alexandre/Desktop/Code/Polytech/ISA%20DevOps/ClientAlum/src/main/resources/AlumWS.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(AlumWebServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/Users/alexandre/Desktop/Code/Polytech/ISA%20DevOps/ClientAlum/src/main/resources/AlumWS.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public AlumWebServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public AlumWebServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public AlumWebServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public AlumWebServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public AlumWebServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public AlumWebServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns AlumWebService
     */
    @WebEndpoint(name = "AlumWebServiceImplPort")
    public AlumWebService getAlumWebServiceImplPort() {
        return super.getPort(AlumWebServiceImplPort, AlumWebService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns AlumWebService
     */
    @WebEndpoint(name = "AlumWebServiceImplPort")
    public AlumWebService getAlumWebServiceImplPort(WebServiceFeature... features) {
        return super.getPort(AlumWebServiceImplPort, AlumWebService.class, features);
    }

}
